### ISSUE TITLE
browser_qwen  问题

### ISSUE THREAD

**Issue by luckierya** [QwenLM/Qwen-Agent#103]
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/86d64e1d-3d5d-43a7-bd46-1807b37724ab)
关于网页的地址问题， 我是模型部署在服务器， qwen agent 也部署在服务器，从mac 本地上传的browser_qwen 文件到扩展程序里，
backgroud.js 中的地址改成了服务器地址，如下
database = "http://172.20.19.12:7866/endpoint"; 一直报上面错误，改成127.0.01 也同样报这个错误，想问下这个改怎么解决呀？怎么实现呀？谢谢

**Comment by tuhahaha** [comment]
直接在这个界面的下面这个框里输入172.20.19.12，不用修改代码内的ip

**Comment by luckierya** [comment]
好的，谢谢，我试下，代码里是127.0.0.1 ， 是不是还改成127.0.0.1 呀？

**Comment by luckierya** [comment]
2024-03-28 21:39:14,296 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:14,296 - utils.py - 43 - ERROR - Traceback (most recent call last):
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
    content = read_text_from_file(path)
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
    with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

2024-03-28 21:39:26,468 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:26,469 - utils.py - 43 - ERROR - Traceback (most recent call last):
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
    content = read_text_from_file(path)
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
    with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

2024-03-28 21:39:38,703 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:38,704 - utils.py - 43 - ERROR - Traceback (most recent call last):
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
    content = read_text_from_file(path)
  File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
    with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

**Comment by luckierya** [comment]
您好，浏览器插件在网页问答时除了 arxiv 可以外，在其他所有浏览器的网页都浏览不了，
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/4b15c070-31a0-438c-9a70-6bbb74d15ce0)
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/04d73ce6-ccfe-4a74-aefb-2767caa9be08)
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/c3e422db-0c17-46d3-a330-eafb90ae59f4)
感觉这个地址是错的，不知道为什么是这样的地址

**Comment by luckierya** [comment]
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/453eea19-0faa-42da-8d20-d6aac22b14fd)
<img width="1085" alt="image" src="https://github.com/QwenLM/Qwen-Agent/assets/164475087/8e5a2280-2fe2-42f8-b61b-e826b0037e26">
地址是对的，但是没有回复出答案

**Comment by luckierya** [comment]
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/4bbc5355-42a3-4c8e-b223-a94cce881206)
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/ef3a9938-d79d-428e-83ef-95f6ee0c1743)
cha jian插件显示是错误的

**Comment by Modas-Li** [comment]
设置地址后，浏览器助手变空白
![image](https://github.com/QwenLM/Qwen-Agent/assets/40042370/bb91807d-6e6f-4bde-9510-741a1b79cc11)

**Comment by Modas-Li** [comment]
端口需要怎么调整呢？哪些是linux机器必须开通的呢

**Comment by Modas-Li** [comment]
生成的图片如何修改IP地址呢？
![image](https://github.com/QwenLM/Qwen-Agent/assets/40042370/4fc9b8d5-5e13-4604-aaf0-86d7afc8bb3f)
