### ISSUE TITLE
插件不能访问网页问题

### ISSUE THREAD

**Issue by luckierya** [QwenLM/Qwen-Agent#105]
2024-03-28 21:39:14,296 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:14,296 - utils.py - 43 - ERROR - Traceback (most recent call last):
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
content = read_text_from_file(path)
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

2024-03-28 21:39:26,468 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:26,469 - utils.py - 43 - ERROR - Traceback (most recent call last):
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
content = read_text_from_file(path)
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

2024-03-28 21:39:38,703 - assistant_server.py - 79 - INFO - The current access page is: workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8
2024-03-28 21:39:38,704 - utils.py - 43 - ERROR - Traceback (most recent call last):
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 142, in get_file_type
content = read_text_from_file(path)
File "/data2/zmy/qwen/Qwen-Agent/qwen_agent/utils/utils.py", line 128, in read_text_from_file
with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/download/f0561de405c7ede6d4bd98553ad5561274509d3927bf7cba3882d150c00fe6f8'

**Comment by luckierya** [comment]
您好，浏览器插件在网页问答时除了 arxiv 可以外，在其他所有浏览器的网页都浏览不了，
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/49d20cba-5f35-4e4e-af7e-6d648d67b480)
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/41c3349d-5108-4f07-b801-2b6b15c7fd00)
这个地址是错的，不知道为什么是这个地址

**Comment by luckierya** [comment]
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/8adbc194-9d87-45e6-8362-20caddce733a)
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/ff602f86-fe63-4403-9452-53dd8567591d)
插件报是错的

**Comment by tuhahaha** [comment]
你好，看起来是你的远程服务器没接收到数据，可以尝试在有浏览器的电脑上运行后台服务，看下能否正确进行网页问答

**Comment by luckierya** [comment]
@tuhahaha 感谢回复，我是在远程服务器上linux 上起的这个agent 程序， qwen 72B 也是在这个服务器上运行的， 插件是在mac 本地运行的。 chage 了地址到服务器上。是这个程序需要在mac 本地运行才行吗？还有就是我如果是想都在远程服务器：比如192.20.19.22 这个服务器上运行的话需要怎么改才可以呀？

**Comment by luckierya** [comment]
server.config 
{
    "path": {
        "work_space_root": "workspace/",
        "database_root": "workspace/database/",
        "download_root": "workspace/download/",
        "code_interpreter_ws": "workspace/ci_workspace/"
    },
    "server": {
        "server_host": "0.0.0.0",
        "fast_api_port": 7866,
        "app_in_browser_port": 7863,
        "workstation_port": 7864,
        "model_server": "http://192.20.19.22:8000/v1",
        "api_key": "",
        "llm": "qwen-72b-chat",
        "max_ref_token": 4000,
        "max_days": 7,
        "functions": [
            "code_interpreter",
            "image_gen"
        ]
    }
}

**Comment by luckierya** [comment]
run_server.py
  parser.add_argument('-s',
                        '--server_host',
                        type=str,
                        default='0.0.0.0',
                        choices=['127.0.0.1', '0.0.0.0'])
    parser.add_argument(
        '-t',

**Comment by luckierya** [comment]
backgroup.js 远程是这么配置的
function send_data(msg){
    chrome.storage.local.get(['database_host'], function(result) {
        if (result.database_host) {
            console.log('database_host currently is ' + result.database_host);
            database = "http://"+result.database_host+":7866/endpoint";
        } else {
            database = "http://127.0.0.1:7866/endpoint";
        }
        fetch(database, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify(msg),
        })
          .then((response) => response.json())
          .then((data) => {
            console.log(data.result);
          });
     });
}
本地mac 的backgroup.js 是下面的
        console.log('database_host currently is ' + result.database_host);
            database = "http://"+result.database_host+":7866/endpoint";
        } else {
            database = "http://127.0.0.1:7866/endpoint";
        }
        fetch(database, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify(msg),
        })
   您好，我想问下是我的配置问题吗？
 @tuhahaha

**Comment by luckierya** [comment]
@tuhahaha 
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/a3563ca8-72a3-4adb-bc12-3561242f2158)
您好，服务部署到本地，浏览器也是上传到本地mac的google 浏览器，还是不行，
![image](https://github.com/QwenLM/Qwen-Agent/assets/164475087/978c522f-ef9a-4f3a-b69d-f29c8ab02d46)
No such file or directory: 'workspace/download/2ec50c35d162d54bcc06aab96f7591f1ebb6e7caaecfd9a56b3b8a471256fe30'

**Comment by Modas-Li** [comment]
data server改在mac上运行呢？

**Comment by luckierya** [comment]
@Modas-Li 是一样的，不知道是不是IP的配置问题，对网页的问答，打开百度文档问答都是 workspace/download,不是 http://
www.baidu.com

**Comment by luckierya** [comment]
@Modas-Li 您好，我现在就是在mac 上启动的qwen agent 服务， 在远程服务上启动的qwen 72B chat 的api

**Comment by luckierya** [comment]
您好，这个在本地mac 上启动的 qwen agent服务， 在远程服务器上起的 qwen 的api. 网页不能正常加载



在 2024-03-29 16:08:11，"Jianhong Tu" ***@***.***> 写道：

你好，看起来是你的远程服务器没接收到数据，可以尝试在有浏览器的电脑上运行后台服务，看下能否正确进行网页问答

**Comment by PHPSJ** [comment]
上面问题解决了吗？
