### ISSUE TITLE
demo 运行报错

### ISSUE THREAD

**Issue by EvilCalf** [QwenLM/Qwen-Agent#124]
(base) apple@APPLEdeMacBook-Pro Qwen-Agent % python -u "/Users/apple/Projects/Python/qwen_agent_demo.py"
2024-04-12 12:17:40,468 - memory.py - 84 - INFO - {"keywords_zh": ["画", "绘制", "狗", "宠物", "动物"], "keywords_en": ["draw", "draw a picture", "dog", "pet", "animal"]}

2024-04-12 12:17:40,470 - doc_parser.py - 74 - INFO - Starting cache pages...
2024-04-12 12:17:40,566 - utils.py - 43 - ERROR - Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/tools/doc_parser.py", line 167, in call
    record = self.db.get(hash_sha256(params['url']))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/tools/storage.py", line 72, in get
    return read_text_from_file(os.path.join(path, key))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/utils/utils.py", line 128, in read_text_from_file
    with open(path, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/default_doc_parser_data_path/ef2fc01c4f4fb95b44920a7fd6014df9ed003269683b1f58b8b43d1f828071db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/tools/doc_parser.py", line 97, in process_file
    pdf_content = parse_doc(pdf_path)
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/utils/doc_parser.py", line 39, in parse_doc
    text = extract_text(path)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pdfminer/high_level.py", line 162, in extract_text
    with open_filename(pdf_file, "rb") as fp, StringIO() as output_string:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pdfminer/utils.py", line 53, in __init__
    self.file_handler: AnyIO = open(filename, *args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/apple/Projects/Python/resource/doc.pdf'

Traceback (most recent call last):
  File "/Users/apple/Projects/Python/qwen_agent_demo.py", line 90, in <module>
    test()
  File "/Users/apple/Projects/Python/qwen_agent_demo.py", line 85, in test
    for response in bot.run(messages=messages):
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/agent.py", line 88, in run
    for rsp in self._run(messages=new_messages, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/agents/assistant.py", line 45, in _run
    new_messages = self._prepend_knowledge_prompt(messages, lang,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/agents/assistant.py", line 65, in _prepend_knowledge_prompt
    knowledge = format_knowledge_to_source_and_content(knowledge)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/utils/utils.py", line 310, in format_knowledge_to_source_and_content
    docs = json5.loads(result)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/json5/lib.py", line 108, in loads
    raise ValueError(err)
ValueError: <string>:1 Unexpected "A" at column 1

**Comment by JianxinMa** [comment]
注意看这行报错：FileNotFoundError: [Errno 2] No such file or directory: '/Users/apple/Projects/Python/resource/doc.pdf'

Qwen-Agent/examples下有一些demo会读取 Qwen-Agent/examples/resource/下的文件（只是为了方便写示例，实际用于生产时不需要这么做），可以仔细读下demo的代码。

**Comment by EvilCalf** [comment]
> 注意看这行报错：FileNotFoundError: [Errno 2] No such file or directory: '/Users/apple/Projects/Python/resource/doc.pdf'
> 
> Qwen-Agent/examples下有一些demo会读取 Qwen-Agent/examples/resource/下的文件（只是为了方便写示例，实际用于生产时不需要这么做），可以仔细读下demo的代码。
感谢你的帮助，修改后可以执行了。我在demo中实验修改后，又遇到一个新问题。
`Traceback (most recent call last):
  File "/Users/apple/Projects/Python/qwen_agent_demo.py", line 91, in <module>
    test()
  File "/Users/apple/Projects/Python/qwen_agent_demo.py", line 85, in test
    for response in bot.run(messages=messages):
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/agent.py", line 88, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "/opt/anaconda3/lib/python3.11/site-packages/qwen_agent/agents/fncall_agent.py", line 66, in _run
    use_tool, action, action_input, _ = self._detect_tool(response[-1])
                                                          ~~~~~~~~^^^^
IndexError: list index out of range`

**Comment by JianxinMa** [comment]
@EvilCalf 我猜测是模型输出 空 了（这个情况如果使用方法正确的话，发生概率应该极其低才对）。

输出空时，截图这里的代码没处理好，应该改成：
```py
            if output:
                response.extend(output)
                messages.extend(output)
                use_tool, action, action_input, _ = self._detect_tool(response[-1])
            else:
                use_tool = False
```

我看了眼您的调用示例，发现导致空的原因是您的while循环少写了 等待用户输入 的逻辑，应该改成：
```py
def test(query: str = "画一个山水画"):
    # Define the agent
    bot = init_agent_service()
    # Chat
    messages=[]
    while True:
        query = input('请输入用户问题：')                      # 请看这一行！！！
        messages.append({"role": "user", "content": query})    # 请看这一行！！！
        response=[]
        for response in bot.run(messages=messages):
            print("bot response:", response)
        messages.extend(response)
```

**Comment by EvilCalf** [comment]
@JianxinMa 是的，我后来看了一下，现在是每次调用都会判断最后一句话的role么，这部分代码我还没有找到。以及在一次agent调用过程中，哪部分是判断任务是否完成终结的，能麻烦也指引我一下么，万分感谢

**Comment by JianxinMa** [comment]
> @JianxinMa 是的，我后来看了一下，现在是每次调用都会判断最后一句话的role么，这部分代码我还没有找到。以及在一次agent调用过程中，哪部分是判断任务是否完成终结的，能麻烦也指引我一下么，万分感谢

1. 现在是每次调用都会判断最后一句话的role么 —— 没有。您这个case是模型认为它的回答已经是完整的了，因此输出空（我们会优化下报错）。
2. 在一次agent调用过程中，哪部分是判断任务是否完成终结的 —— 对大部分agents而言，一次 agent.run 结束（内部会调用多次llm，判断是否需要多次调用 llm 的逻辑在 agent._run 里），就意味着agent认为它的任务完成了。如果需要再次调用 agent.run ，就需要再次提供一条 role=user 的消息（人给agent的反馈）再调用 agent.run。
