### ISSUE TITLE
max_input_tokens随着文档长度增加？

### ISSUE THREAD

**Issue by maxin9966** [QwenLM/Qwen-Agent#192]
限定死max_input_tokens为16K，现在只要文档长度超出一定范围，就报错：

2024-06-11 02:12:34,741 - parallel_doc_qa.py - 187 - INFO - Parallel Member Num: 142
2024-06-11 02:13:36,918 - parallel_doc_qa.py - 197 - INFO - Finished parallel_exec. Time spent: 62.17440700531006 seconds.
2024-06-11 02:13:37,360 - utils.py - 69 - ERROR - Traceback (most recent call last):
  File "C:\Users\ma\anaconda3\envs\bot\lib\site-packages\qwen_agent\agents\doc_qa\parallel_doc_qa.py", line 93, in _retrieve_according_to_member_responses
    *_, last = keygen.run([Message(USER, query)])
  File "C:\Users\ma\anaconda3\envs\bot\lib\site-packages\qwen_agent\agent.py", line 87, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "C:\Users\ma\anaconda3\envs\bot\lib\site-packages\qwen_agent\agents\keygen_strategies\gen_keyword.py", line 69, in _run
    return self._call_llm(messages=messages)
qwen_agent.llm.base.ModelServiceError:
Error code: 400. Error message: The input messages exceed the maximum context length (16000 tokens) after keeping only the system message and the latest one user message (around 23311 tokens). To configure the context limit, please specifiy "max_input_tokens" in the model generate_cfg. Example: generate_cfg = {..., "max_input_tokens": 23400}

**Comment by JialinWangPKU** [comment]
您好，这里的问题是keygen的输入过长。https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/doc_qa/parallel_doc_qa.py#L91

parallel-docqa-agent的使用场景是文本问答，主要针对文档中的某个具体问题的问答，且未针对"总结/全文纠错/改写全文"等场景做优化。对于超长文本来说，如果所提的问题需要遍历全文，且每个member预期都会有输出（例如总结全文），这时会导致member_res拼接过长。那么在走rag阶段的keyword_gen以及keyword_search就会受到影响

对于keygen输入限制问题，我们有做新的设置和改动。

对于超长文本“总结/全文纠错”等场景的优化，我们可能会在将来开放新的Agent处理。

**Comment by linnnff** [comment]
> 您好，这里的问题是keygen的输入过长。https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/doc_qa/parallel_doc_qa.py#L91
> 
> parallel-docqa-agent的使用场景是文本问答，主要针对文档中的某个具体问题的问答，且未针对"总结/全文纠错/改写全文"等场景做优化。对于超长文本来说，如果所提的问题需要遍历全文，且每个member预期都会有输出（例如总结全文），这时会导致member_res拼接过长。此时，我们不建议keyword-gen会有超长输入，因为对于长文本，提取keyword的效果也不够理想。那么在后续阶段的keyword_gen以及keyword_search就会受到影响
> 
> 对于keygen输入限制问题，我们有做新的设置和改动，稍后会更新代码。
> 
> 对于超长文本“总结/全文纠错”等场景的优化，我们可能会在将来开放新的Agent处理。

请问修改了吗

**Comment by JialinWangPKU** [comment]
代码已更新，可以拉取main分支体验。
