### ISSUE TITLE
怎样能将较大的数据集喂给ReActChat？ files 有什么作用

### ISSUE THREAD

**Issue by QuintinTao** [QwenLM/Qwen-Agent#261]
我想把一个890KB 的csv 文件给ReActChat，让它帮我分析，并按照我的要求生成图表。我发现给它样本数据 几十条可以，用全量（890kb）的文件就会报token超出。怎么上传大文件进行分析
024-07-09 17:17:56,565 - utils.py - 156 - INFO - Downloading d:\python\qw\qwen-agent\examples\resource\restaurant_data.csv to workspace\tools\code_interpreter\restaurant_data.csv...
2024-07-09 17:17:56,565 - utils.py - 175 - INFO - Finished downloading \python\qw\qwen-agent\examples\resource\restaurant_data.csv to workspace\tools\code_interpreter\restaurant_data.csv. Time spent: 0.0 seconds.
Traceback (most recent call last):
  File "d:\python\qw\Qwen-Agent\examples\assistant_fork_join.py", line 139, in <module>
    advice()
  File "d:\python\qw\Qwen-Agent\examples\assistant_fork_join.py", line 59, in advice
    queries = test(suggestions, file_ful)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\qw\qwen-agent\examples\react_data_analysis_qt.py", line 62, in test
    for response in bot.run(messages):
  File "d:\python\qw\qwen-agent\qwen_agent\agent.py", line 94, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "d:\python\qw\qwen-agent\qwen_agent\agents\react_chat.py", line 69, in _run
    for output in self._call_llm(messages=text_messages):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\qw\qwen-agent\qwen_agent\agent.py", line 148, in _call_llm
    return self.llm.chat(messages=messages,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\qw\qwen-agent\qwen_agent\llm\base.py", line 97, in chat
    messages = _truncate_input_messages_roughly(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\python\qw\qwen-agent\qwen_agent\llm\base.py", line 345, in _truncate_input_messages_roughly
    raise ModelServiceError(
qwen_agent.llm.base.ModelServiceError: 
Error code: 400. Error message: The input messages exceed the maximum context length (5800 tokens) after keeping only the system message and the latest one user message (around 27121 tokens). To configure the context limit, please specifiy "max_input_tokens" in the model generate_cfg. Example: generate_cfg = {..., "max_input_tokens": 27200}

**Comment by JianxinMa** [comment]
ReActChat的files的主要功能是传给code interpreter（用于让大模型执行python代码的工具）；ReActChat没有引入RAG等支持。

**Comment by QuintinTao** [comment]
> ReActChat的files的主要功能是传给code interpreter（用于让大模型执行python代码的工具）；ReActChat没有引入RAG等支持。

您好，那如果想喂给大模型数据，量稍微大一点，怎么做呢？给个思路
