### ISSUE TITLE
httpx.ConnectTimeout: _ssl.c:989: The handshake operation timed out

### ISSUE THREAD

**Issue by guhao17** [QwenLM/Qwen-Agent#276]
如题，我之前运行run_server还好好的，今天就报了这个错误
(qwen) D:\idata\Qwen-Agent>python run_server.py --llm qwen2:7b --model_server http://localhost:11434/v1/ --api_key EMPTY
2024-07-17 16:10:53,837 - run_server.py - 101 - INFO - path=PathConfig(work_space_root='workspace/', download_root='workspace/download/', code_interpreter_ws='workspace/tools/code_interpreter/') server=ServerConfig(server_host='127.0.0.1', fast_api_port=7866, app_in_browser_port=7863, workstation_port=7864, model_server='http://localhost:11434/v1/', api_key='EMPTY', llm='qwen2:7b', max_ref_token=4000, max_days=7)
2024-07-17 16:10:55,011 - database_server.py - 34 - INFO - 10.8.6.223
2024-07-17 16:10:55,048 - database_server.py - 34 - INFO - 10.8.6.223
INFO:     Started server process [8820]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7866 (Press CTRL+C to quit)
Running on local URL:  http://127.0.0.1:7863
Running on local URL:  http://127.0.0.1:7864

To create a public link, set `share=True` in `launch()`.

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-5 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "D:\Anaconda\envs\qwen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\qwen\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\qwen\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\gradio\analytics.py", line 70, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\gradio\analytics.py", line 131, in get_local_ip_address
    ip_address = httpx.get(
                 ^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_api.py", line 198, in get
    return request(
           ^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "D:\Anaconda\envs\qwen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:989: The handshake operation timed out
Exception in thread Thread-5 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "D:\Anaconda\envs\qwen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\qwen\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\qwen\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\gradio\analytics.py", line 70, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\gradio\analytics.py", line 131, in get_local_ip_address
    ip_address = httpx.get(
                 ^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_api.py", line 198, in get
    return request(
           ^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "D:\Anaconda\envs\qwen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\qwen\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:989: The handshake operation timed out

**Comment by PHPSJ** [comment]
+1

**Comment by JianxinMa** [comment]
这个看起来像是 gradio 版本的问题。试试
```
pip install "gradio==4.21.0" "modelscope-studio>=0.4.0"
```
看问题是否有解决。如果没有，辛苦提供下复现的方法~
