### ISSUE TITLE
0.0.7版本是不是有bug？0.0.6正常的代码，升级一下版本报错了

### ISSUE THREAD

**Issue by zml0506-163** [QwenLM/Qwen-Agent#304]
2024-08-07 09:42:37,405 - utils.py - 69 - ERROR - Traceback (most recent call last):
  File "E:\work\autoSmartData\autoSmartData\venv\Lib\site-packages\qwen_agent\utils\utils.py", line 226, in get_file_type
    content = read_text_from_file(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\autoSmartData\autoSmartData\venv\Lib\site-packages\qwen_agent\utils\utils.py", line 187, in read_text_from_file
    file_content = file.read()
                   ^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 15: invalid start byte

2024-08-07 09:42:37 - 19396 - qwen_agent_logger - ERROR - Traceback (most recent call last):
  File "E:\work\autoSmartData\autoSmartData\venv\Lib\site-packages\qwen_agent\utils\utils.py", line 226, in get_file_type
    content = read_text_from_file(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\work\autoSmartData\autoSmartData\venv\Lib\site-packages\qwen_agent\utils\utils.py", line 187, in read_text_from_file
    file_content = file.read()
                   ^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 15: invalid start byte

**Comment by JianxinMa** [comment]
感谢提醒。不过这个报错看起来更像是0.0.6会有、而0.0.7不该有的报错，因为0.0.7在utils.py里做了如下改动：
```diff
 def read_text_from_file(path: str) -> str:
-    with open(path, 'r', encoding='utf-8') as file:
-        file_content = file.read()
+    try:
+        with open(path, 'r', encoding='utf-8') as file:
+            file_content = file.read()
+    except UnicodeDecodeError:
+        print_traceback(is_error=False)
+        from charset_normalizer import from_path
+        results = from_path(path)
+        file_content = str(results.best())
     return file_content
```
预期应该会catch掉您遇到的这个UnicodeDecodeError异常。。

同时从您的报错“line 187, in read_text_from_file”看，这个行号line 187和0.0.7好像对不上，反而和0.0.6对应上了。= =
