### ISSUE TITLE
对parallel_doc_qa.py不做修改，直接运行，在网站上传了一个400w tokens的斗破苍穹的txt文件，并进行了提问，但是报错

### ISSUE THREAD

**Issue by lvchong-del** [QwenLM/Qwen-Agent#307]
下面是终端运行日志 UnicodeDecodeError可以忽略，我在运行assistant_rag.py文件上传同样的txt文件也有这个错误，但是正常运行并能输入结果。
/home/Qwen-Agent/examples# python parallel_doc_qa.py 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.21.0, however version 4.29.0 is available, please upgrade.
--------
2024-08-09 11:24:38,838 - parallel_doc_qa.py - 180 - INFO - user_question: 萧炎最终什么等级
2024-08-09 11:24:38,847 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/utils/utils.py", line 201, in read_text_from_file
    file_content = file.read()
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 59: invalid start byte

2024-08-09 11:26:55,122 - doc_parser.py - 99 - INFO - Read chunked /tmp/gradio/54278df3d7f97419159d5877c36d0aad09218a1b/doupocangqiong_tiancantudou.txt from cache.
2024-08-09 11:26:55,124 - parallel_doc_qa.py - 200 - INFO - Parallel Member Num: 4424
2024-08-09 11:27:10,310 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/llm/base.py", line 425, in retry_model_service_iterator
    for rsp in it_fn():
  File "/home/Qwen-Agent/qwen_agent/llm/qwen_dashscope.py", line 111, in _full_stream_output
    raise ModelServiceError(code=chunk.code, message=chunk.message)
qwen_agent.llm.base.ModelServiceError: 
Error code: Throttling.RateQuota. Error message: Requests rate limit exceeded, please try again later.

2024-08-09 11:27:10,553 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/llm/base.py", line 425, in retry_model_service_iterator
    for rsp in it_fn():
  File "/home/Qwen-Agent/qwen_agent/llm/qwen_dashscope.py", line 111, in _full_stream_output
    raise ModelServiceError(code=chunk.code, message=chunk.message)
qwen_agent.llm.base.ModelServiceError: 
Error code: Throttling.RateQuota. Error message: Requests rate limit exceeded, please try again later.

2024-08-09 11:27:11,018 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/llm/base.py", line 425, in retry_model_service_iterator
    for rsp in it_fn():
  File "/home/Qwen-Agent/qwen_agent/llm/qwen_dashscope.py", line 111, in _full_stream_output
    raise ModelServiceError(code=chunk.code, message=chunk.message)
qwen_agent.llm.base.ModelServiceError: 
Error code: Throttling.RateQuota. Error message: Requests rate limit exceeded, please try again later.

2024-08-09 11:27:11,256 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/llm/base.py", line 425, in retry_model_service_iterator
    for rsp in it_fn():
  File "/home/Qwen-Agent/qwen_agent/llm/qwen_dashscope.py", line 111, in _full_stream_output
    raise ModelServiceError(code=chunk.code, message=chunk.message)
qwen_agent.llm.base.ModelServiceError: 
Error code: Throttling.RateQuota. Error message: Requests rate limit exceeded, please try again later.

之后就一直报这个Throttling.RateQuota错误。
感谢解答！
![Uploading 屏幕截图 2024-08-09 113231.png…]()

**Comment by JianxinMa** [comment]
Error code: Throttling.RateQuota. Error message: Requests rate limit exceeded, please try again later.

这个是阿里云模型服务的报错，原因是：处理400w tokens需要请求非常多次模型服务，但阿里云那边对请求频率做了限制。一般建议用私有化部署的模型服务、或者用assistant_rag.py这个成本更低的rag方案。

**Comment by lvchong-del** [comment]
好的，感谢！
还有一个问题就是在运行assistant_rag.py时，我在第一次提问时上传了这个txt文件，等待了4分钟后回答了问题。接着我问了第二个问题，但是还是等待了4分钟后才回答了问题，这个是正常现象吗。我在问题[#209](url)看到了您的回答是运行这个rag文件是不需要等待时间的
![屏幕截图 2024-08-09 115409](https://github.com/user-attachments/assets/4d4b2441-d8e3-4302-9741-c061a7b2250f)
