### ISSUE TITLE
使用其他的大模型运行parallel_doc_qa.py，输入txt文件(70w字符)。运行错误：ValueError: not enough values to unpack (expected at least 1, got 0)

### ISSUE THREAD

**Issue by lvchong-del** [QwenLM/Qwen-Agent#310]
终端运行日志
To create a public link, set `share=True` in `launch()`.
2024-08-12 12:43:42,755 - parallel_doc_qa.py - 185 - INFO - user_question: 说明一下甄嬛的职位变化
2024-08-12 12:43:42,758 - utils.py - 73 - WARNING - Traceback (most recent call last):
  File "/home/Qwen-Agent/qwen_agent/utils/utils.py", line 201, in read_text_from_file
    file_content = file.read()
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 0: invalid continuation byte

2024-08-12 12:44:17,756 - simple_doc_parser.py - 320 - INFO - Read parsed /tmp/gradio/96af7270aee70ecb938c82030ae12adad06b43150479630070fdb679e1eaf1cf/shiyizhang.txt from cache.
2024-08-12 12:44:17,758 - doc_parser.py - 114 - INFO - Start chunking /tmp/gradio/96af7270aee70ecb938c82030ae12adad06b43150479630070fdb679e1eaf1cf/shiyizhang.txt (shiyizhang.txt)...
2024-08-12 12:44:17,979 - doc_parser.py - 132 - INFO - Finished chunking /tmp/gradio/96af7270aee70ecb938c82030ae12adad06b43150479630070fdb679e1eaf1cf/shiyizhang.txt (shiyizhang.txt). Time spent: 0.219984769821167 seconds.
2024-08-12 12:44:17,998 - parallel_doc_qa.py - 205 - INFO - Parallel Member Num: 1461
下面是把parallel_exec（）函数运行的结果逐条打印出来了
(1415, '{"res": "none", "content": "<None>"}')
(1262, '{"res": "none", "content": "<None>"}')
(412, '{"res": "none", "content": "<None>"}')
(1251, '{"res": "none", "content": "<None>"}')
(1435, '{"res": "none", "content": "<None>"}')
(667, '{"res": "none", "content": "<None>"}')
(1413, '{"res": "none", "content": "<None>"}')
(1326, '{"res": "none", "content": "<None>"}')
(825, '{"res": "none", "content": "<None>"}')
(1307, '{"res": "none", "content": "<None>"}')
(1174, '{"res": "none", "content": "<None>"}')
(448, '{"res": "none", "content": "<None>"}')
(1097, '{"res": "none", "content": "<None>"}')
(1128, '{"res": "none", "content": "<None>"}')
(92, '{"res": "none", "content": "<None>"}')
(1120, '{"res": "none", "content": "<None>"}')
(642, '{"res": "none", "content": "<None>"}')
(1056, '{"res": "none", "content": "<None>"}')
(420, '{"res": "none", "content": "<None>"}')
(1412, '{"res": "none", "content": "<None>"}')
...
(478, '{"res": "none", "content": "<None>"}')
(135, '{"res": "none", "content": "<None>"}')
(1377, '{"res": "ans", "content": "当今天子的宠妃"}')
(1001, '{"res": "ans", "content": "我被废去所有封号和位份逐出棠梨宫退居京郊的甘露寺带修行。"}')
(273, '{"res": "none", "content": "<None>"}')
(1289, '{"res": "none", "content": "<None>"}')
(699, '{"res": "none", "content": "<None>"}')
(1191, '{"res": "none", "content": "<None>"}')
(354, '{"res": "none", "content": "<None>"}')
(914, '{"res": "none", "content": "<None>"}')
(1400, '{"res": "ans", "content": "去岁选秀那么不过一年之间已从从五品的小仪一跃而至从三品的婕妤"}')
(1388, '{"res": "none", "content": "<None>"}')
(940, '和文档内容无关，无法回答关于甄嬛职位变化的问题。\n\n{"res": "none", "content": "<None>"}')
(579, '{"res": "none", "content": "<None>"}')
(1296, '{"res": "none", "content": "<None>"}')
...
(1196, '{"res": "none", "content": "<None>"}')
(604, '{"res": "ans", "content": "新晋了莞贵嫔"}')
(1294, '{"res": "none", "content": "<None>"}')
(1438, '{"res": "ans", "content": "用太后的一句话说若做帝姬就是一辈子的享福尊贵。"}')
(1195, '{"res": "none", "content": "<None>"}')
(1430, '{"res": "none", "content": "<None>"}')
(1399, '{"res": "none", "content": "<None>"}')
(1343, '{"res": "none", "content": "<None>"}')
(1302, '{"res": "none", "content": "<None>"}')
(1230, '{"res": "none", "content": "<None>"}')
(421, '回答这个问题需要了解甄嬛在文档中的职位变化情况。然而，文档中并没有直接提及甄嬛的职位或职位变化，只是描述了她与皇上的对话以及她在宫中的行为和想法。因此，无法根据文档内容回答甄嬛的职位变化。\n\n```json\n{"res": "none", "content": "<None>"}')
...
(543, '{"res": "ans", "content": "我晋为贵嫔掌一宫事宜"}')
(17, '{"res": "ans", "content": "著封为正六品贵人"}')
(16, '{"res": "none", "content": "<None>"}')
(975, '{"res": "none", "content": "<None>"}')
(964, '{"res": "none", "content": "<None>"}')
...
(492, '{"res": "none", "content": "<None>"}')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1931, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1528, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "/home/Qwen-Agent/qwen_agent/gui/web_ui.py", line 225, in agent_run
    for responses in agent_runner.run(_history, **self.run_kwargs):
  File "/home/Qwen-Agent/qwen_agent/agent.py", line 94, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "/home/Qwen-Agent/qwen_agent/agents/doc_qa/parallel_doc_qa.py", line 212, in _run
    results = parallel_exec(self._ask_member_agent, data, jitter=0.5)
  File "/home/Qwen-Agent/qwen_agent/utils/parallel_executor.py", line 39, in parallel_exec
    print(future.result())
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/Qwen-Agent/qwen_agent/agents/doc_qa/parallel_doc_qa.py", line 252, in _ask_member_agent
    *_, last = doc_qa.run(messages=messages, knowledge=knowledge, lang=lang, instruction=instruction)
ValueError: not enough values to unpack (expected at least 1, got 0)

这个错误是否和输入文本的字符数有关呢，我测试了10w到40w的字符数都能够成功运行。
感谢回答！

**Comment by JianxinMa** [comment]
看了下，应该是 doc_qa.run 返回空 [] 了（对应的是底下的llm模型服务返回空 []）了。可能 llm 服务有报错、断联了？

**Comment by sirizhou** [comment]
我也遇到了同样问题，我使用的本地部署的qwen2.5 32B
