### ISSUE TITLE
运行qwen2vl_function_calling.py 报 Multiple multimodal inputs is currently not supported

### ISSUE THREAD

**Issue by yunfucheng** [QwenLM/Qwen-Agent#336]
文件地址 https://github.com/QwenLM/Qwen-Agent/blob/main/examples/qwen2vl_function_calling.py
Qwen-Agent 是git clone 本地安装的 时间20240909

# Function Response:
{'role': 'function', 'name': 'image_gen', 'content': [ContentItem({'image': './pic.jpg'}), ContentItem({'text': '（ 这张图片的URL是 ./pic.jpg ）'})]}
# Assistant Response 2:
Traceback (most recent call last):
  File "d:\apps\qwen-agent\qwen_agent\llm\oai.py", line 74, in _chat_stream
    response = self._chat_complete_create(model=self.model, messages=messages, stream=True, **generate_cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\apps\qwen-agent\qwen_agent\llm\oai.py", line 62, in _chat_complete_create
    return client.chat.completions.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\qwenv\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\qwenv\Lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\qwenv\Lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\qwenv\Lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "D:\ProgramData\Miniconda3\envs\qwenv\Lib\site-packages\openai\_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Multiple multimodal inputs is currently not supported.', 'type': 'BadRequestError', 'param': None, 'code': 400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Projects\Python\QwenVL\qwen2vl_function_calling.py", line 96, in <module>
    test()
  File "d:\Projects\Python\QwenVL\qwen2vl_function_calling.py", line 90, in test
  File "d:\apps\qwen-agent\qwen_agent\llm\base.py", line 288, in _convert_messages_iterator_to_target_type    for messages in messages_iter:
  File "d:\apps\qwen-agent\qwen_agent\llm\base.py", line 268, in _postprocess_messages_iterator
    for pre_msg in messages:
  File "d:\apps\qwen-agent\qwen_agent\llm\base.py", line 444, in retry_model_service_iterator
    num_retries, delay = _raise_or_delay(e, num_retries, delay, max_retries)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\apps\qwen-agent\qwen_agent\llm\base.py", line 458, in _raise_or_delay
    raise e
  File "d:\apps\qwen-agent\qwen_agent\llm\base.py", line 439, in retry_model_service_iterator
    for rsp in it_fn():
  File "d:\apps\qwen-agent\qwen_agent\llm\oai.py", line 86, in _chat_stream
    raise ModelServiceError(exception=ex)
qwen_agent.llm.base.ModelServiceError: Error code: 400 - {'object': 'error', 'message': 'Multiple multimodal inputs is currently not supported.', 'type': 'BadRequestError', 'param': None, 'code': 400}

**Comment by JianxinMa** [comment]
您好，请确认下llm_cfg是否有指定`'model_type': 'qwenvl_dashscope',`（使用阿里云提供的模型服务） 或 `'model_type': 'qwenvl_oai',`（使用自己部署的模型服务）。

**Comment by yunfucheng** [comment]
> 您好，请确认下llm_cfg是否有指定`'model_type': 'qwenvl_dashscope',`（使用阿里云提供的模型服务） 或 `'model_type': 'qwenvl_oai',`（使用自己部署的模型服务）。

有的。以下是例子完整文件：


import json
import os
import urllib.parse

from qwen_agent.llm import get_chat_model
from qwen_agent.llm.schema import ContentItem
from qwen_agent.utils.utils import save_url_to_local_work_dir


def image_gen(prompt: str) -> str:
    prompt = urllib.parse.quote(prompt)
    image_url = f'https://image.pollinations.ai/prompt/{prompt}'
    image_url = save_url_to_local_work_dir(image_url, save_dir='./', save_filename='pic.jpg')
    return image_url


def test():
    # Config for the model
    llm_cfg_oai = {
        # Using Qwen2-VL deployed at any openai-compatible service such as vLLM:
        'model_type': 'qwenvl_oai',
        'model': 'Qwen',
        'model_server': 'http://localhost:8000/v1',  # api_base
        'api_key': 'EMPTY',

        # Using Qwen2-VL provided by Alibaba Cloud DashScope's openai-compatible service:
        # 'model_type': 'qwenvl_oai',
        # 'model': 'qwen-vl-max-0809',
        # 'model_server': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        # 'api_key': os.getenv('DASHSCOPE_API_KEY'),

        # Using Qwen2-VL provided by Alibaba Cloud DashScope:
        # 'model_type': 'qwenvl_dashscope',
        # 'model': 'qwen-vl-max-0809',
        # 'api_key': os.getenv('DASHSCOPE_API_KEY'),
        # 'generate_cfg': dict(max_retries=10,)
    }
    llm = get_chat_model(llm_cfg_oai)

    # Initial conversation
    messages = [{
        'role':
            'user',
        'content': [{
            'image': 'https://dashscope.oss-cn-beijing.aliyuncs.com/images/dog_and_girl.jpeg'
        }, {
            'text': '图片中的内容是什么？请画一张内容相同，风格类似的图片。把女人换成男人'
        }]
    }]

    functions = [
        {
            'name': 'image_gen',
            'description': 'AI绘画（图像生成）服务，输入文本描述，返回根据文本信息绘制的图片URL。',
            'parameters': {
                'name': 'prompt',
                'type': 'string',
                'description': '详细描述了希望生成的图像具有什么内容，例如人物、环境、动作等细节描述，使用英文',
                'required': True
            }
        },
    ]

    print('# Assistant Response 1:')
    responses = []
    for responses in llm.chat(messages=messages, functions=functions, stream=True):
        print(responses)
    messages.extend(responses)

    for rsp in responses:
        if rsp.get('function_call', None):
            func_name = rsp['function_call']['name']
            if func_name == 'image_gen':
                func_args = json.loads(rsp['function_call']['arguments'])
                image_url = image_gen(func_args['prompt'])
                print('# Function Response:')
                func_rsp = {
                    'role': 'function',
                    'name': func_name,
                    'content': [ContentItem(image=image_url),
                                ContentItem(text=f'（ 这张图片的URL是 {image_url} ）')],
                }
                messages.append(func_rsp)
                print(func_rsp)
            else:
                raise NotImplementedError

    print('# Assistant Response 2:')
    responses = []
    for responses in llm.chat(messages=messages, functions=functions, stream=True):
        print(responses)
    messages.extend(responses)


if __name__ == '__main__':
    test()

**Comment by JianxinMa** [comment]
您好，我尝试用我自己的qwen2vl模型服务复现，没能复现该错误。

您遇到的报错
```
qwen_agent.llm.base.ModelServiceError: Error code: 400 - {'object': 'error', 'message': 'Multiple multimodal inputs is currently not supported.', 'type': 'BadRequestError', 'param': None, 'code': 400}
```
是来自您部署的vllm模型服务的报错。请确认该模型是 qwen2-vl 的模型，而不是纯文本的qwen模型。

**Comment by yunfucheng** [comment]
> 您好，我尝试用我自己的qwen2vl模型服务复现，没能复现该错误。
> 
> 您遇到的报错
> 
> ```
> qwen_agent.llm.base.ModelServiceError: Error code: 400 - {'object': 'error', 'message': 'Multiple multimodal inputs is currently not supported.', 'type': 'BadRequestError', 'param': None, 'code': 400}
> ```
> 
> 是来自您部署的vllm模型服务的报错。请确认该模型是 qwen2-vl 的模型，而不是纯文本的qwen模型。


这个确实不是百分百报出来的，因为我第一次的时候也是没有报出来
我的整体步骤

1. 运行 examples/qwen2vl_function_calling.py 正常输出
2. 运行 examples/qwen2vl_assistant_tooluse.py 时报了该错误
3. 再次运行 examples/qwen2vl_function_calling.py 时报了该错误

**Comment by JianxinMa** [comment]
咨询了我们的同事 @fyabc ，vllm openai api server多图支持是今天的vllm版本刚刚更新的（而而阿里云dashscope的模型服务一直支持多图），需要等我们的同事更新下docker。
 
@fyabc 更新好了docker后，如方便的话，辛苦在此issue说明下已更新。

**Comment by yunfucheng** [comment]
> 咨询了我们的同事 @fyabc ，vllm openai api server多图支持是今天的vllm版本刚刚更新的（而而阿里云dashscope的模型服务一直支持多图），需要等我们的同事更新下docker。
> 
> @fyabc 更新好了docker后，如方便的话，辛苦在此issue说明下已更新。

好咧

**Comment by fyabc** [comment]
> 咨询了我们的同事 @fyabc ，vllm openai api server多图支持是今天的vllm版本刚刚更新的（而而阿里云dashscope的模型服务一直支持多图），需要等我们的同事更新下docker。
> 
> @fyabc 更新好了docker后，如方便的话，辛苦在此issue说明下已更新。

@yunfucheng  您好，docker镜像已更新，支持多图推理，注意需要在启动`vllm.entrypoints.openai.api_server`时加上`--limit-mm-per-prompt image=10`类似的参数修改默认的每条请求图像数量最大值。

具体可参考[此处](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#notes)

@JianxinMa
