### ISSUE TITLE
运行demo，将模型换成本地Ollama部署的模型会报错404 Not Found

### ISSUE THREAD

**Issue by qingqinghu1026** [QwenLM/Qwen-Agent#394]
执行examples/parallel_doc_qa.py demo， 将llm换成
bot = ParallelDocQA(llm={'model': 'gs_qwen:7b-chat',
                             'model_server': 'http://IP:11433',
                             'api_key': 'EMPTY',
    # Use a model service compatible with the OpenAI API, such as vLLM or Ollama:
    # 'model': 'Qwen2-7B-Chat',
    # 'model_server': 'http://localhost:8000/v1',  # base_url, also known as api_base
    # 'api_key': 'EMPTY',
                            #  'generate_cfg': {
                            #      'max_retries': 10}
                            }
                        )
执行会报错
Traceback (most recent call last):
  File "/home/qqhu/workdir/ml/OpenAI/Qwen-Agent/qwen_agent/llm/oai.py", line 77, in _chat_stream
    response = self._chat_complete_create(model=self.model, messages=messages, stream=True, **generate_cfg)
  File "/home/qqhu/workdir/ml/OpenAI/Qwen-Agent/qwen_agent/llm/oai.py", line 63, in _chat_complete_create
    return client.chat.completions.create(*args, **kwargs)
  File "/home/qqhu/anaconda3/envs/py39/lib/python3.9/site-packages/openai/_utils/_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
  File "/home/qqhu/anaconda3/envs/py39/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
  File "/home/qqhu/anaconda3/envs/py39/lib/python3.9/site-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/qqhu/anaconda3/envs/py39/lib/python3.9/site-packages/openai/_base_client.py", line 853, in request
    return self._request(
  File "/home/qqhu/anaconda3/envs/py39/lib/python3.9/site-packages/openai/_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
是什么原因呢

该链接使用client是可以正常使用的，正常使用代码
client = Client(host='http://IP:11433')
load_dotenv()

def llmresponse(messages):    
    try:
        response = client.chat(
            model = 'qwen2:7b',  #llama3:latest    gs_qwen:7b-chat   yi:9b  qwen2:7b
            messages = messages,
        )
        out = response['message']['content'].strip()
    except Exception as e:
        print(e)
        out = 'llmresponse error'
    return out

**Comment by wangsiyu666** [comment]
llm下面不要使用Azure OpenAI API创建Client，使用OpenAI API创建client可以解决

**Comment by tuhahaha** [comment]
您好，看起来是Ollama的接口访问方式和oai的不同，先尝试下把model_server 改成http://ip:11433/v1，这个似乎是适配oai的接口

**Comment by qingqinghu1026** [comment]
修改为[http://ip:11433/v1]也不行
该用vLLM部署大模型，可以调用了

**Comment by tuhahaha** [comment]
好的，那我就先close这个issue了
