### ISSUE TITLE
执行报错UnicodeDecodeError: 'gbk' codec can't decode byte 0x89 in position 2407: illegal multibyte sequence

### ISSUE THREAD

**Issue by nulinuli-nuli** [QwenLM/Qwen-Agent#407]
Traceback (most recent call last):
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\qwen_agent\gui\gradio_dep.py", line 4, in <module>
    import modelscope_studio.components.base as ms
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\modelscope_studio\__init__.py", line 1, in <module>
    from .components.antd.components import *
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\modelscope_studio\components\antd\__init__.py", line 45, in <module>
    from .float_button import AntdFloatButton as FloatButton
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\modelscope_studio\components\antd\float_button\__init__.py", line 8, in <module>
    from .back_top import AntdFloatButtonBackTop
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\modelscope_studio\components\antd\float_button\back_top\__init__.py", line 10, in <module>
    class AntdFloatButtonBackTop(ModelScopeLayoutComponent):
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\gradio\component_meta.py", line 218, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "D:\pythonProject\first_agent\.venv\Lib\site-packages\gradio\component_meta.py", line 133, in create_or_modify_pyi
    current_interface, _ = extract_class_source_code(pyi_file.read_text(), class_name)
                                                     ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x89 in position 2407: illegal multibyte sequence

**Comment by tuhahaha** [comment]
Hello, it seems that there is a encoding compatibility issue on Windows with the package modelscope_studio. We will fix it as soon as possible.

**Comment by tuhahaha** [comment]
hi, we have fixed this issue, can you try again?

**Comment by nulinuli-nuli** [comment]
Successful，thanks
