### ISSUE TITLE
在Windows环境下尝试使用dashcode（直接用第二步）遇到如下错误

### ISSUE THREAD

**Issue by yumingfan-0219** [QwenLM/Qwen-Agent#45]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1497, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1131, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 653, in gen_wrapper
    yield from f(*args, **kwargs)
  File qwen-agent\Qwen-Agent-main\Qwen-Agent-main\qwen_server\assistant_server.py", line 68, in bot
    set_page_url()
  File \qwen-agent\Qwen-Agent-main\Qwen-Agent-main\qwen_server\assistant_server.py", line 60, in set_page_url
    assert os.path.exists(cache_file_popup_url)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by yumingfan-0219** [comment]
同时这样会使得7864打不开。不过后来发现gradio降级到3.41就能解决，建议在requirement中==限制一下

**Comment by tuhahaha** [comment]
好的，感谢建议，我修改下～
