### ISSUE TITLE
代码执行器报错了ipykernel

### ISSUE THREAD

**Issue by skyblue4cn** [QwenLM/Qwen-Agent#46]
WARNING:  WatchFiles detected changes in 'workspace\ci_workspace\launch_kernel_17084.py'. Reloading...
Traceback (most recent call last):                                                                                    
  File "E:\LangChain-ChatGLM-Webui\env1\Qwen-Agent\workspace\ci_workspace\launch_kernel_17084.py", line 2, in <module>
Traceback (most recent call last):                                                                                    
  File "E:\LangChain-ChatGLM-Webui\env1\Qwen-Agent\qwen_server/assistant_server.py", line 201, in <module>            
    from ipykernel import kernelapp as app                                                                            
Traceback (most recent call last):                                                                                    
  File "E:\LangChain-ChatGLM-Webui\env1\Qwen-Agent\qwen_server/workstation_server.py", line 670, in <module>          
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    demo.queue().launch(server_name=server_config.server.server_host,
    from .connect import *  # noqa
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\gradio\blocks.py", line 2118, in launch
    ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\ipykernel\connect.py", line 12, in <module>
    demo.queue().launch(server_name=server_config.server.server_host,
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\gradio\blocks.py", line 2118, in launch
    import jupyter_client
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\jupyter_client\__init__.py", line 3, in <module>
    self.block_thread()
    from .asynchronous import AsyncKernelClient
    self.block_thread()
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\gradio\blocks.py", line 2202, in block_thread
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\gradio\blocks.py", line 2202, in block_thread
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    time.sleep(0.1)
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\jupyter_client\asynchronous\client.py", line 8, in <module>
TypeError: _kill_kernels() takes 0 positional arguments but 2 were given
    time.sleep(0.1)
    import zmq.asyncio
TypeError: _kill_kernels() takes 0 positional arguments but 2 were given
  File "E:\LangChain-ChatGLM-Webui\env1\Lib\site-packages\zmq\asyncio.py", line 9, in <module>
    import asyncio
  File "C:\python\Lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\python\Lib\asyncio\base_events.py", line 18, in <module>
    import concurrent.futures
  File "C:\python\Lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\python\Lib\concurrent\futures\_base.py", line 7, in <module>
    import logging
  File "C:\python\Lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "C:\python\Lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\python\Lib\linecache.py", line 11, in <module>
INFO:     Shutting down
    import tokenize
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
KeyboardInterrupt

**Comment by skyblue4cn** [comment]
自己提的问题自己解决，因为workspace/ci_workspace/目录在gradio目录下，gradio有热加载，当执行python代码时，gradio会重启web服务，实属坑爹！！！解决方案是关掉热加载或者换ci_workspace的目录。

**Comment by tuhahaha** [comment]
workspace/ci_workspace/应该是在项目根目录下，gradio目录下具体是指哪个目录呢？
