### ISSUE TITLE
我使用fastchat部署的api服务调用不通

### ISSUE THREAD

**Issue by erjiguan** [QwenLM/Qwen-Agent#49]
为了多gpu推理，我用https://github.com/QwenLM/Qwen/blob/main/README_CN.md#%E9%83%A8%E7%BD%B2
的方法部署api服务，但是用agent对话的时候，api调不通。
Traceback (most recent call last):
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/qwen/agent/Qwen-Agent/qwen_server/workstation_server.py", line 317, in bot
    for chunk in response:
  File "/root/qwen/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 22, in _chat_stream
    response = openai.ChatCompletion.create(model=self.model,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.5/lib/python3.11/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"Only Qwen-14B-Chat allowed now, your model qwen-turbo","code":40301}' (HTTP response code was 400)
**这个是fastchat的api_server的报错**
![17ef70e6ad200a7a52f47bb22f7ac93](https://github.com/QwenLM/Qwen-Agent/assets/41512143/cec4dcd4-7bfa-4744-bc8c-53b1699407b6)

**Comment by JianxinMa** [comment]
根据`Only Qwen-14B-Chat allowed now, your model qwen-turbo` 这个报错，猜测是需要 `python run_server.py` 时指定下 `--llm Qwen-14B-Chat`.
