### ISSUE TITLE
正常启动，过程发现报错，如下，应该是这个文件不存在。cache_file_popup_url

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen-Agent#60]
AssertionError
Traceback (most recent call last):
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/luxi.lm/Desktop/cache/Qwen-Agent/qwen_server/assistant_server.py", line 68, in bot
    set_page_url()
  File "/Users/luxi.lm/Desktop/cache/Qwen-Agent/qwen_server/assistant_server.py", line 60, in set_page_url
    assert os.path.exists(cache_file_popup_url)
AssertionError

**Comment by tuhahaha** [comment]
你是在网页端问答时候遇到的这个问题吗？我将本地cache_file_popup_url对应的文件删除后，运行python run_server.py后可以正常启动，然后在网页端添加页面问答会正常新建这个文件。多数情况下不会出现文件不存在的情况，你再尝试一次？

**Comment by xrenaissance** [comment]
这个问题又出现了

**Comment by tcexeexe** [comment]
我也遇到了这个问题
