### ISSUE TITLE
部署完毕服务后，发现测试调用，好像流试不太兼容openai接口，openai我版本是0.28

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen-Agent#61]
代码：
```
import logging
import json
import openai

openai.api_base = "http://0.0.0.0:7905/v1"
openai.api_key = "none"


def call_qwen(messages, functions=None, stream=False):
    print(f"messages\r\n{messages}")
    if functions:
        response = openai.ChatCompletion.create(
            model="Qwen", messages=messages, functions=functions
        )
    else:
        response = openai.ChatCompletion.create(model="Qwen", messages=messages,stream=stream)
    # print(f"response\r\n{json.dumps(response, ensure_ascii=False, indent=4)}")
    return response


if __name__ == "__main__":
    messages = [{"role": "user", "content": "你好"}]
    # response = call_qwen(messages)
    # print(response)
    response = call_qwen(messages,stream=True)
    for r in response:
        print(r)
```

报错：
messages
[{'role': 'user', 'content': '你好'}]
Traceback (most recent call last):
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line
    data = json.loads(rbody)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example/llm_tools_serve_eg1.py", line 36, in <module>
    response = call_qwen(messages,stream=True)
  File "example/llm_tools_serve_eg1.py", line 25, in call_qwen
    response = openai.ChatCompletion.create(model="Qwen", messages=messages,stream=stream)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/Users/luxi.lm/opt/miniconda3/envs/Etuning/lib/python3.8/site-packages/openai/api_requestor.py", line 757, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 200 from API (data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"role":"assistant"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"你好"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"！"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"有什么"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"我能"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"帮助"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"你的"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"吗"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{"content":"？"},"finish_reason":null}]}

data: {"model":"Qwen","object":"chat.completion.chunk","choices":[{"index":0,"delta":{},"finish_reason":"stop"}]}

data: [DONE]

)

**Comment by wellcasa** [comment]
# Name                    Version                   Build  Channel
openai                    0.28.1                   pypi_0    pypi
