### ISSUE TITLE
浏览器插件对话功能正常，但是当需要进行网页分析的时候，报错requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### ISSUE THREAD

**Issue by tcexeexe** [QwenLM/Qwen-Agent#66]
您好，目前模型和数据库部署在局域网内的服务器上，设置防火墙关闭。在笔记本使用插件时，对话功能ok，但是当需要进行网页分析和对话时，agent服务出现报错如下。已经在Customize Address中输入了局域网中的服务器IP地址，不知问题出现在哪里
```
Traceback (most recent call last):
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/tcexeexe/dataDisk1/mycode/Qwen-Agent/qwen_server/assistant_server.py", line 102, in bot
    for chunk in response:
  File "/home/tcexeexe/dataDisk1/mycode/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 29, in _chat_stream
    for chunk in response:
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 168, in <genexpr>
    return (
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/openai/api_requestor.py", line 702, in <genexpr>
    return (
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/openai/api_requestor.py", line 116, in parse_stream
    for line in rbody:
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/home/tcexeexe/anaconda3/envs/qwen/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by tuhahaha** [comment]
你好，看起来像是模型回复失败。如果你是本地机器部署的Qwen，可以看下是否报错OOM，如果是，可以调小max_ref_token为3000试试 @tcexeexe

**Comment by tcexeexe** [comment]
好的，确实是显存OOM的问题，谢谢！
