### ISSUE TITLE
[BUG] <title>code interpreter is not working

### ISSUE THREAD

**Issue by ruifengma** [QwenLM/Qwen-Agent#72]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Other chat is normal . Only when I try to use code interpreter, the error raised:
```
2024-01-26 14:45:45,054 - utils.py - 35 - ERROR - Traceback (most recent call last):
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 137, in _support_function_calling
    *_, last = self._chat_with_functions(messages=messages,
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 185, in _postprocess_iterator
    yield self._postprocess_convert_text_to_fncall(m)
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 283, in _postprocess_convert_text_to_fncall
    messages = self._format_msg_to_list(messages)
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 191, in _format_msg_to_list
    role = msg[ROLE]
TypeError: string indices must be integers

2024-01-26 14:45:45,054 - qwen_oai.py - 70 - INFO - Detected function calls are not supported, using chat format
Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 712, in _error_catcher
    yield
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1071, in read_chunked
    self._update_chunk_length()
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1006, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 931, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1059, in read_chunked
    with self._error_catcher():
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 243, in bot
    for chunk in output_beautify.convert_to_full_str_stream(
  File "/data/mrx/agent/Qwen-Agent/qwen_server/output_beautify.py", line 81, in convert_to_full_str_stream
    for message_list in message_list_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/agents/assistant.py", line 91, in _run
    for output in output_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 184, in _postprocess_iterator
    for m in messages:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 42, in _chat_stream
    for chunk in response:
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 168, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_requestor.py", line 702, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_requestor.py", line 116, in parse_stream
    for line in rbody:
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 251, in bot
    raise ValueError(ex)
ValueError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

```
and the error on the Qwen model side is
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/data/mrx/agent/Qwen/openai_api.py", line 442, in predict
    raise HTTPException(
fastapi.exceptions.HTTPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 83, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
```

### 期望行为 | Expected Behavior

Just want it to run normally

### 复现方法 | Steps To Reproduce

just pull the latest code base from Qwen and run with openai_api.py to deploy and run the run_server.py from QwenAgent

### 运行环境 | Environment

```Markdown
- OS:CentOS7
- Python:3.10
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by JianxinMa** [comment]
@tuhahaha Plz look into this issue.

**Comment by tuhahaha** [comment]
Hi, the code has been updated now and code interpreter can run correctly. Please pull the latest code to run @xrenaissance @ruifengma @

**Comment by ruifengma** [comment]
Thanks @tuhahaha, currently the error has been fixed but the stream responding is still not working.

**Comment by tuhahaha** [comment]
Currently streaming output is supported. Are you referring to non-streaming as the result of code execution, i.e. Observation? @ruifengma

**Comment by ruifengma** [comment]
@tuhahaha the whole responding process is non-streaming in Code interpreter mode (except pure chat and Document QA). It's like, when I send meg, I need to wait for a while, and I got a complete response all in once (Thought, Action, Action input, Code Execution, Observation). DO I need to switch something to activate streaming mode in Code Interpreter?

**Comment by ruifengma** [comment]
Find something from the log, don't know if this is helpful for you to locate the issue @tuhahaha 
```
INFO:     Started server process [24084]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
2024-01-30 11:06:10,388 - qwen_oai.py - 69 - WARNING - This method does not support stream=True, Simulate using stream=False!
```

**Comment by tuhahaha** [comment]
Hello, this function should not run in the latest version of the code. Please update the code and execute it again? @ruifengma

**Comment by ruifengma** [comment]
@tuhahaha Yes, I have updated the code already with the latest version and it's quite wired with this streaming issue.

**Comment by xrenaissance** [comment]
> @tuhahaha Yes, I have updated the code already with the latest version and it's quite wired with this streaming issue.

I had same issue as well

**Comment by ruifengma** [comment]
@tuhahaha With the latest Qwen repo and Qwen Agent repo at this moment, I now go back to the original error (first issue), nothing works, even pure chat

**Comment by tuhahaha** [comment]
Could you please paste the error log? It's running fine on my end.

**Comment by ruifengma** [comment]
@tuhahaha sure
error log from Qwen openai_api.py side
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 15/15 [00:08<00:00,  1.73it/s]
INFO:     Started server process [59594]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8195 (Press CTRL+C to quit)
INFO:     127.0.0.1:41048 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/data/mrx/agent/Qwen/openai_api.py", line 488, in predict
    raise HTTPException(
fastapi.exceptions.HTTPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 83, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
```
from the Qwen agent side
```
2024-01-31 10:10:08,360 - run_server.py - 90 - INFO - path=PathConfig(work_space_root='workspace/', database_root='workspace/database/', download_root='workspace/download/', code_interpreter_ws='workspace/ci_workspace/') server=ServerConfig(server_host='0.0.0.0', fast_api_port=7866, app_in_browser_port=7863, workstation_port=8192, model_server='http://127.0.0.1:8195/v1', api_key='', llm='qwen-plus', max_ref_token=4000, max_days=7, functions=['code_interpreter', 'image_gen'])
2024-01-31 10:10:10,091 - database_server.py - 31 - INFO - 10.76.170.155
INFO:     Will watch for changes in these directories: ['/data/mrx/agent/Qwen-Agent']
INFO:     Uvicorn running on http://0.0.0.0:7866 (Press CTRL+C to quit)
INFO:     Started reloader process [59793] using StatReload
/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py:812: UserWarning: Expected 1 arguments for function <function clear_session at 0x7f157ccf39a0>, received 0.
  warnings.warn(
/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py:816: UserWarning: Expected at least 1 arguments for function <function clear_session at 0x7f157ccf39a0>, received 0.
  warnings.warn(
Running on local URL:  http://0.0.0.0:7863

To create a public link, set `share=True` in `launch()`.
Running on local URL:  http://0.0.0.0:8192

To create a public link, set `share=True` in `launch()`.
2024-01-31 10:10:11,771 - database_server.py - 31 - INFO - 10.76.170.155
2024-01-31 10:10:11,790 - database_server.py - 31 - INFO - 10.76.170.155
INFO:     Started server process [59995]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Traceback (most recent call last):
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 712, in _error_catcher
    yield
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 1071, in read_chunked
    self._update_chunk_length()
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 1006, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 931, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 1059, in read_chunked
    with self._error_catcher():
  File "/root/miniconda3/envs/qwen177/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/urllib3/response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 251, in bot
    for chunk in output_beautify.convert_to_full_str_stream(
  File "/data/mrx/agent/Qwen-Agent/qwen_server/output_beautify.py", line 81, in convert_to_full_str_stream
    for message_list in message_list_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/agents/react_chat.py", line 64, in _run
    for output in output_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 42, in _chat_stream
    for chunk in response:
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 168, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/openai/api_requestor.py", line 702, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/openai/api_requestor.py", line 116, in parse_stream
    for line in rbody:
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/qwen177/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 259, in bot
    raise ValueError(ex)
ValueError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
don't know why, but it seems just go back to the origin
this is my dependency info:
```
Package                       Version
----------------------------- ------------
accelerate                    0.25.0
aiofiles                      23.2.1
aiohttp                       3.9.1
aiosignal                     1.3.1
altair                        5.2.0
annotated-types               0.6.0
anyio                         3.7.1
argilla                       1.12.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         23.1.0
Babel                         2.14.0
backoff                       2.2.1
beautifulsoup4                4.12.2
bleach                        6.1.0
certifi                       2023.11.17
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cmake                         3.25.0
comm                          0.2.0
commonmark                    0.9.1
contourpy                     1.2.0
cryptography                  41.0.7
cycler                        0.12.1
dashscope                     1.13.6
dataclasses-json              0.6.3
debugpy                       1.8.0
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
docx2txt                      0.8
einops                        0.7.0
et-xmlfile                    1.1.0
exceptiongroup                1.2.0
executing                     2.0.1
fastapi                       0.105.0
fastjsonschema                2.19.0
ffmpy                         0.3.1
filelock                      3.13.1
filetype                      1.2.0
fonttools                     4.47.0
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2023.12.2
gradio                        3.50.2
gradio_client                 0.6.1
greenlet                      3.0.2
h11                           0.14.0
html2text                     2020.1.16
httpcore                      0.16.3
httpx                         0.23.3
huggingface-hub               0.19.4
idna                          3.6
importlib-resources           6.1.1
ipykernel                     6.27.1
ipython                       8.18.1
ipywidgets                    8.1.1
isoduration                   20.11.0
jedi                          0.19.1
jieba                         0.42.1
Jinja2                        3.1.2
joblib                        1.3.2
json5                         0.9.14
jsonlines                     4.0.0
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.20.0
jsonschema-specifications     2023.11.2
jupyter                       1.0.0
jupyter_client                8.6.0
jupyter-console               6.6.3
jupyter_core                  5.5.1
jupyter-events                0.9.0
jupyter-lsp                   2.2.1
jupyter_server                2.12.1
jupyter_server_terminals      0.5.0
jupyterlab                    4.0.9
jupyterlab_pygments           0.3.0
jupyterlab_server             2.25.2
jupyterlab-widgets            3.0.9
kiwisolver                    1.4.5
langchain                     0.0.351
langchain-community           0.0.4
langchain-core                0.1.1
langsmith                     0.0.72
lit                           15.0.7
lxml                          4.9.3
Markdown                      3.5.1
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.2
matplotlib-inline             0.1.6
mistune                       3.0.2
monotonic                     1.6
mpmath                        1.3.0
msg-parser                    1.2.0
multidict                     6.0.4
mypy-extensions               1.0.0
nbclient                      0.9.0
nbconvert                     7.13.0
nbformat                      5.9.2
nest-asyncio                  1.5.8
networkx                      3.2.1
nltk                          3.8.1
notebook                      7.0.6
notebook_shim                 0.2.3
numpy                         1.23.5
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
olefile                       0.47
openai                        0.28.1
openpyxl                      3.1.2
orjson                        3.9.10
overrides                     7.4.0
packaging                     23.2
pandas                        1.5.3
pandocfilters                 1.5.0
parso                         0.8.3
pdf2image                     1.16.3
pdfminer.six                  20221105
pexpect                       4.9.0
Pillow                        10.1.0
pip                           23.3.1
platformdirs                  4.1.0
prometheus-client             0.19.0
prompt-toolkit                3.0.43
psutil                        5.9.7
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
pydantic                      2.5.2
pydantic_core                 2.14.5
pydub                         0.25.1
Pygments                      2.17.2
pypandoc                      1.12
pyparsing                     3.1.1
pypdf                         3.17.3
python-dateutil               2.8.2
python-docx                   1.1.0
python-json-logger            2.0.7
python-magic                  0.4.27
python-multipart              0.0.6
python-pptx                   0.6.23
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         25.1.2
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.32.0
regex                         2023.10.3
requests                      2.31.0
rfc3339-validator             0.1.4
rfc3986                       1.5.0
rfc3986-validator             0.1.1
rich                          13.0.1
rpds-py                       0.15.2
safetensors                   0.4.1
scikit-learn                  1.3.2
scipy                         1.11.4
seaborn                       0.13.0
semantic-version              2.10.0
Send2Trash                    1.8.2
setuptools                    68.2.2
six                           1.16.0
sniffio                       1.3.0
soupsieve                     2.5
SQLAlchemy                    2.0.23
sse-starlette                 1.8.2
stack-data                    0.6.3
starlette                     0.27.0
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
terminado                     0.18.0
threadpoolctl                 3.2.0
tiktoken                      0.5.2
tinycss2                      1.2.1
tokenizers                    0.13.3
tomli                         2.0.1
toolz                         0.12.0
torch                         2.0.0+cu118
torchvision                   0.15.1+cu118
tornado                       6.4
tqdm                          4.66.1
traitlets                     5.14.0
transformers                  4.32.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typer                         0.7.0
types-python-dateutil         2.8.19.14
typing_extensions             4.9.0
typing-inspect                0.9.0
unstructured                  0.8.0
uri-template                  1.3.0
urllib3                       2.1.0
uvicorn                       0.24.0.post1
wcwidth                       0.2.12
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
websockets                    11.0.3
wheel                         0.41.2
widgetsnbextension            4.0.9
wordcloud                     1.9.3
wrapt                         1.14.1
xlrd                          2.0.1
XlsxWriter                    3.1.9
yarl                          1.9.4

```

**Comment by tuhahaha** [comment]
Hello, I have identified the issue as the OAI interface of openai_api.py currently does not support stop word in streaming. We are currently working on a quick fix. A temporary solution you can use is to replace this function with ：

**Comment by tuhahaha** [comment]
Hello, I have identified the issue as the OAI interface of openai_api.py currently does not support stop word in streaming output. We are currently working on a quick fix.

**Comment by ruifengma** [comment]
Thanks @tuhahaha for the effort, looking forward to the update.

**Comment by tuhahaha** [comment]
Hi~ Now it works, please pull the latest Qwen and Qwen-Agent code

**Comment by ruifengma** [comment]
@tuhahaha it works perfectly now, thanks
