### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xxxx/workspace/ci_workspace/test_file_permission.txt'

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen-Agent#79]
(flowise) tskj@tskj:~/Agent-server/$ python run_server.py 
Traceback (most recent call last):
  File "/home/tskj/Agent-server/run_server.py", line 9, in <module>
    from qwen_agent.log import logger
  File "/home/tskj/Agent-server/qwen_agent/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/home/tskj/Agent-server/qwen_agent/agent.py", line 9, in <module>
    from qwen_agent.tools import TOOL_REGISTRY
  File "/home/tskj/Agent-server/qwen_agent/tools/__init__.py", line 3, in <module>
    from .code_interpreter import CodeInterpreter
  File "/home/tskj/Agent-server/qwen_agent/tools/code_interpreter.py", line 48, in <module>
    _fix_secure_write_for_code_interpreter()
  File "/home/tskj/Agent-server/qwen_agent/tools/code_interpreter.py", line 40, in _fix_secure_write_for_code_interpreter
    os.open(fname, os.O_CREAT | os.O_WRONLY | os.O_TRUNC, 0o0600),
FileNotFoundError: [Errno 2] No such file or directory: '/home/tskj/Agent-server/workspace/ci_workspace/test_file_permission.txt'
Ubuntu22.04，新建的python环境，依赖完整，编辑好cfg后启动，搜索了一下issue，发现没有其他人发生这个错误，求教各位大佬！

**Comment by wxhheian** [comment]
同有这个问题，插个眼

**Comment by ye7love7** [comment]
使用以下命令还是一样的报错：sudo /home/tskj/miniconda3/envs/flowise/bin/python run_server.py --model_server http://41.218.128.131:8000 --api_key EMPTY --llm Qwen-14B-Chat --server_host 0.0.0.0 --workstation_port 7864
似乎不是权限问题，老版本是可以正常创建的，用最新的版本反而不行了

**Comment by JianxinMa** [comment]
修复了，遇到该问题的可以拉下新代码。（这几天代码改得频繁，测试不到位，我们会反思下。。）
