### ISSUE TITLE
 将网页添加到qwen的阅读列表中报错

### ISSUE THREAD

**Issue by nowndthen** [QwenLM/Qwen-Agent#89]
服务端报错日志如下：
“2024-03-04 19:47:41,652 - utils.py - 42 - ERROR - Traceback (most recent call last):
  File "/Users/macy_wang/Qwen-Agent/qwen_agent/tools/doc_parser.py", line 106, in process_file
    content = parse_html_bs(file_tmp_path)
  File "/Users/macy_wang/Qwen-Agent/qwen_agent/utils/doc_parser.py", line 76, in parse_html_bs
    pages = loader.load_and_split()
  File "/opt/homebrew/lib/python3.8/site-packages/langchain_community/document_loaders/base.py", line 59, in load_and_split
    docs = self.load()
  File "/opt/homebrew/lib/python3.8/site-packages/langchain_community/document_loaders/html_bs.py", line 50, in load
    soup = BeautifulSoup(f, **self.bs_kwargs)
  File "/opt/homebrew/lib/python3.8/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?”

**Comment by tuhahaha** [comment]
您好，这应该是langchain版本更新了导致，您可以先下载老版本：pip install langchain==0.1.8

**Comment by JianxinMa** [comment]
我看这个报错好像是少了 lxml 这个依赖。试试安装依赖 `pip install lxml` 再重试？

**Comment by JianxinMa** [comment]
刚更新了代码，兼容了最新版langchain，可以pull下代码再试试
